[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
local = 'http://localhost:8545'
goerli = "${GOERLI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
